baseURL = "http://maurosch.github.io/"
languageCode = "es"
title = "Blog Mauro"

author = "Mauro"
canonifyurls = true
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false
publishDir = "docs"

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Blog Mauro"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
  dateform = "02/01/06"
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
#[[menu.primary]]
#    name = "About"
#    url = "/about/"
#    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/maurosch"
    weight = 3
[[menu.primary]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5
